dist: trusty
sudo: required
language: node_js
node_js:
- '8.9.4'
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
cache:
  apt: true
  bundler: true
  directories:
  - node_modules
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- ng build --prod
script:
- ng lint
- ng test --single-run --code-coverage
- ng e2e
