version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10.14-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run ng lint
      - run:
          name: Unit Test
          command: npm run ng test -- --watch=false --code-coverage
      - run:
          name: E2E Test
          command: npm run ng e2e
      - run:
          name: Build
          command: npm run ng build -- --prod
