version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    working_directory: /tmp/dac-angular
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run ng lint
      - run:
          name: Unit Test
          command: npm run ng test -- --watch=false --code-coverage
      - run:
          name: E2E Test
          command: npm run ng e2e
      - run:
          name: Build
          command: npm run ng build -- --prod
  deploy:
    docker:
      - image: circleci/node:8
    working_directory: /tmp/dac-angular
    steps:
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: circleci
