version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.14-browsers
    steps:
      - checkout
      - run:
          name: Hello
          command: echo 'Hello World!'
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install
          command: npm install
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: ng build --prod
